// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SubstrateGeometry",
    platforms: [
        .macOS("11.0"),
        .iOS("14.0"),
        .tvOS("14.0")
    ],
    products: [
        .library(
            name: "SubstrateGeometry",
            targets: ["SubstrateGeometry"]
        ),
        .library(
            name: "MeshOptimizer",
            targets: ["MeshOptimizer"]
        ),
        .library(
            name: "MikkTSpace",
            targets: ["MikkTSpace"]
        ),
        .library(
            name: "cgltf",
            targets: ["cgltf", "cgltfwrite"]
        )
    ],
    dependencies: [
        .package(name: "Substrate", url: "https://github.com/troughton/SubstrateRender", branch: "immediate-mode"),
        .package(name: "CAssimp", url: "https://github.com/troughton/CAssimp", from: "5.0.0"),
    ],
    targets: [
        
        .target(
            name: "MeshOptimizer",
            publicHeadersPath: ""
        ),
        .target(
            name: "cgltf",
            publicHeadersPath: ""
        ),
        .target(
            name: "cgltfwrite",
            dependencies: [
                "cgltf"
            ],
            publicHeadersPath: ""
        ),
        .target(
            name: "MikkTSpace",
            publicHeadersPath: ""
        ),
        .target(
            name: "SubstrateGeometry",
            dependencies: [
                "MeshOptimizer",
                "cgltf",
                "MikkTSpace",
                .product(name: "SubstrateMath", package: "Substrate"),
                .product(name: "CAssimp", package: "CAssimp")
            ]
        )
    ]
)
