// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SubstrateGeometry",
    platforms: [
        .macOS("11.0"),
        .iOS("14.0"),
        .tvOS("14.0")
    ],
    products: [
        .library(
            name: "SubstrateGeometry",
            targets: ["SubstrateGeometry"]
        )
    ],
    dependencies: [
        .package(name: "Substrate", url: "https://github.com/troughton/SubstrateRender", branch: "immediate-mode")
    ],
    targets: [
        .target(
            name: "MeshOptimizer",
            publicHeadersPath: ""
        ),
        .target(
            name: "cgltf",
            publicHeadersPath: ""
        ),
        .target(
            name: "cgltfwrite",
            dependencies: [
                "cgltf"
            ],
            publicHeadersPath: ""
        ),
        .target(
            name: "MikkTSpace",
            publicHeadersPath: ""
        ),
        .target(
            name: "SubstrateGeometry",
            dependencies: [
                "MeshOptimizer",
                "cgltf",
                "MikkTSpace",
                .product(name: "SubstrateMath", package: "Substrate")
            ]
        )
    ]
)
